[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "linker=clang", "-C", "force-unwind-tables=no"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "linker=aarch64-linux-gnu-gcc"]

[net]
git-fetch-with-cli = true

[profile.release]
# Optimize for size
opt-level = "z"
lto = "thin"
