#!/bin/bash
# Fail if the docs site does not describe the version we are shipping.
#
# Between v0.31.0 and v0.32.2 the docs changelog was never updated, so the
# site advertised a release three versions behind the binary. Nothing caught
# it: the release checklist lived in CLAUDE.md as prose, and scripts/release.sh
# only drives `cargo release`, which knows nothing about doc/.
#
# Two invariants, both keyed off `version` in Cargo.toml:
#   1. doc/app/views/home/index.html.slv carries a matching version pill.
#   2. doc/app/views/docs/changelog.html.slv has a section for that version.
#
# Run from the repository root. Used by scripts/release.sh and by CI.

set -euo pipefail

cd "$(dirname "$0")/.."

CHANGELOG_VIEW="doc/app/views/docs/changelog.html.slv"
HOME_VIEW="doc/app/views/home/index.html.slv"

# The [package] version. [workspace] comes first in Cargo.toml and has no
# `version` key, so the first match is the package's.
VERSION="$(grep -m1 '^version' Cargo.toml | cut -d'"' -f2)"

if [ -z "$VERSION" ]; then
    echo "check_docs_sync: could not read version from Cargo.toml" >&2
    exit 1
fi

echo "Cargo.toml version: v$VERSION"

status=0

# --- 1. version pill on the landing page ---------------------------------
if grep -q "ver-pill\">v${VERSION}<" "$HOME_VIEW"; then
    echo "  ok   version pill in $HOME_VIEW"
else
    current="$(grep -o 'ver-pill">v[0-9.]*<' "$HOME_VIEW" | head -1 | sed 's/ver-pill">//;s/<//')"
    echo "  FAIL $HOME_VIEW shows ${current:-nothing}, expected v$VERSION" >&2
    status=1
fi

# --- 2. a changelog section for this version ------------------------------
# Matches the existing markup: <h2 ...>vX.Y.Z</h2>
if grep -qE "<h2[^>]*>v${VERSION}</h2>" "$CHANGELOG_VIEW"; then
    echo "  ok   v$VERSION section in $CHANGELOG_VIEW"
else
    newest="$(grep -oE '<h2[^>]*>v[0-9.]+</h2>' "$CHANGELOG_VIEW" \
              | head -1 | grep -oE 'v[0-9.]+')"
    cat >&2 <<EOF
  FAIL $CHANGELOG_VIEW has no section for v$VERSION (newest is ${newest:-none}).

        Add one, and move anything under "Unreleased" into it. The entry for
        this version in CHANGELOG.md is usually the right source text — it is
        generated by release-please from conventional commits.
EOF
    status=1
fi

# --- 3. unreleased work must be described ---------------------------------
# The two checks above are keyed off the version, so they pass unchanged while
# feature after feature lands between releases — which is how the columnar
# SDBQL work shipped with an Unreleased section that predated it.
#
# This cannot verify the section is *complete*, only that it is not still the
# placeholder while commits exist since the last tag. Needs tags, so CI must
# check out with fetch-depth: 0.
#
# Only applies once the version in Cargo.toml has been tagged. While a release
# is being prepared, Cargo.toml is bumped ahead of the newest tag and the
# entries have just been moved out of Unreleased and into the section for the
# version being shipped — which checks 1 and 2 above have already confirmed
# exists. Demanding a non-placeholder Unreleased then would make cutting a
# release impossible: scripts/release.sh runs this check *before* it tags, and
# so does the CI run for the release commit on main.
if git rev-parse --git-dir >/dev/null 2>&1 && git describe --tags --abbrev=0 >/dev/null 2>&1; then
    last_tag="$(git describe --tags --abbrev=0)"
    commits_since="$(git rev-list --count "${last_tag}..HEAD")"

    if [ "$last_tag" != "v$VERSION" ]; then
        echo "  ok   Unreleased section (releasing v$VERSION, newest tag is $last_tag)"
    elif [ "$commits_since" -gt 0 ] &&
       sed -n '/<!-- Unreleased -->/,/<\/section>/p' "$CHANGELOG_VIEW" \
         | grep -q "No unreleased changes yet"; then
        cat >&2 <<EOF
  FAIL $commits_since commit(s) since $last_tag but the Unreleased section is
        still the placeholder. Describe what changed, or move it into a
        version section if you are cutting a release.
EOF
        status=1
    else
        echo "  ok   Unreleased section ($commits_since commit(s) since $last_tag)"
    fi
fi

if [ "$status" -ne 0 ]; then
    echo >&2
    echo "docs site is out of sync — see the failures above." >&2
    exit 1
fi

echo "docs site is in sync with v$VERSION"
