#!/bin/bash
# Fail if the docs site does not describe the version we are shipping.
#
# Between v0.31.0 and v0.32.2 the docs changelog was never updated, so the
# site advertised a release three versions behind the binary. Nothing caught
# it: the release checklist lived in CLAUDE.md as prose, and scripts/release.sh
# only drives `cargo release`, which knows nothing about doc/.
#
# Three invariants, all keyed off `version` in Cargo.toml:
#   1. the version pill partial (doc/app/views/shared/_version_pill.html.slv)
#      matches, and the landing page and docs layout render it.
#   2. doc/app/views/docs/changelog.html.slv has a section for that version.
#   3. CHANGELOG.md has a section for that version.
#
# Invariant 3 was added on 2026-09-20: v1.1.1 was tagged by hand rather than
# through release-please, so CHANGELOG.md skipped the version entirely while
# checks 1 and 2 stayed green — the docs site described a release the
# repository's own changelog did not mention.
#
# Run from the repository root. Used by scripts/release.sh and by CI.

set -euo pipefail

cd "$(dirname "$0")/.."

CHANGELOG_VIEW="doc/app/views/docs/changelog.html.slv"
HOME_VIEW="doc/app/views/home/index.html.slv"
CHANGELOG_MD="CHANGELOG.md"

# The [package] version. [workspace] comes first in Cargo.toml and has no
# `version` key, so the first match is the package's.
VERSION="$(grep -m1 '^version' Cargo.toml | cut -d'"' -f2)"

if [ -z "$VERSION" ]; then
    echo "check_docs_sync: could not read version from Cargo.toml" >&2
    exit 1
fi

echo "Cargo.toml version: v$VERSION"

status=0

# --- 1. the version pill ---------------------------------------------------
# The pill is written once, in a partial that the landing page and the docs
# layout both render. Before that each carried its own copy, and the layout was
# missed by the release checklist: every docs page showed the previous version.
PILL_PARTIAL="doc/app/views/shared/_version_pill.html.slv"
if grep -q "ver-pill\">v${VERSION}<" "$PILL_PARTIAL"; then
    echo "  ok   version pill in $PILL_PARTIAL"
else
    current="$(grep -o 'ver-pill">v[0-9.]*<' "$PILL_PARTIAL" | head -1 | sed 's/ver-pill">//;s/<//')"
    echo "  FAIL $PILL_PARTIAL shows ${current:-nothing}, expected v$VERSION" >&2
    status=1
fi

# No view may carry a literal pill of its own; it must render the partial.
stray="$(grep -rl 'class="ver-pill"' doc/app/views | grep -v "^$PILL_PARTIAL$" || true)"
if [ -n "$stray" ]; then
    echo "  FAIL a version pill is hardcoded outside $PILL_PARTIAL (use partial(\"shared/version_pill\", {})):" >&2
    echo "$stray" | sed 's/^/         /' >&2
    status=1
else
    echo "  ok   no hardcoded version pill outside the partial"
fi
for view in doc/app/views/home/index.html.slv doc/app/views/layouts/docs.html.slv; do
    if grep -q 'shared/version_pill' "$view"; then
        echo "  ok   $view renders the pill partial"
    else
        echo "  FAIL $view does not render shared/version_pill" >&2
        status=1
    fi
done

# --- 2. a changelog section for this version ------------------------------
# Matches the existing markup: <h2 ...>vX.Y.Z</h2>
if grep -qE "<h2[^>]*>v${VERSION}</h2>" "$CHANGELOG_VIEW"; then
    echo "  ok   v$VERSION section in $CHANGELOG_VIEW"
else
    newest="$(grep -oE '<h2[^>]*>v[0-9.]+</h2>' "$CHANGELOG_VIEW" \
              | head -1 | grep -oE 'v[0-9.]+')"
    cat >&2 <<EOF
  FAIL $CHANGELOG_VIEW has no section for v$VERSION (newest is ${newest:-none}).

        Add one, and move anything under "Unreleased" into it. The entry for
        this version in CHANGELOG.md is usually the right source text — it is
        generated by release-please from conventional commits.
EOF
    status=1
fi

# --- 2b. a CHANGELOG.md section for this version ---------------------------
# Same invariant as check 2, on the repository's own changelog. release-please
# normally writes this section from the conventional commits, so it is already
# present on a generated release; a release tagged by hand is what this catches.
if grep -qE "^## \\[${VERSION}\\]" "$CHANGELOG_MD"; then
    echo "  ok   $VERSION section in $CHANGELOG_MD"
else
    newest_md="$(grep -oE '^## \[[0-9]+\.[0-9]+\.[0-9]+\]' "$CHANGELOG_MD" \
                 | head -1 | tr -d '#[] ')"
    cat >&2 <<EOF
  FAIL $CHANGELOG_MD has no section for $VERSION (newest is ${newest_md:-none}).

        release-please generates these from conventional commits. If the
        release was tagged by hand, write the section yourself and say so in
        it — copy the text from $CHANGELOG_VIEW.
EOF
    status=1
fi

# --- 3. unreleased work must be described ---------------------------------
# The two checks above are keyed off the version, so they pass unchanged while
# feature after feature lands between releases — which is how the columnar
# SDBQL work shipped with an Unreleased section that predated it.
#
# This cannot verify the section is *complete*, only that it is not still the
# placeholder while commits exist since the last tag. Needs tags, so CI must
# check out with fetch-depth: 0.
#
# Only applies once the version in Cargo.toml has been tagged. While a release
# is being prepared, Cargo.toml is bumped ahead of the newest tag and the
# entries have just been moved out of Unreleased and into the section for the
# version being shipped — which checks 1 and 2 above have already confirmed
# exists. Demanding a non-placeholder Unreleased then would make cutting a
# release impossible: scripts/release.sh runs this check *before* it tags, and
# so does the CI run for the release commit on main.
if git rev-parse --git-dir >/dev/null 2>&1 && git describe --tags --abbrev=0 >/dev/null 2>&1; then
    last_tag="$(git describe --tags --abbrev=0)"
    commits_since="$(git rev-list --count "${last_tag}..HEAD")"

    if [ "$last_tag" != "v$VERSION" ]; then
        echo "  ok   Unreleased section (releasing v$VERSION, newest tag is $last_tag)"
    elif [ "$commits_since" -gt 0 ] &&
       sed -n '/<!-- Unreleased -->/,/<\/section>/p' "$CHANGELOG_VIEW" \
         | grep -q "No unreleased changes yet"; then
        cat >&2 <<EOF
  FAIL $commits_since commit(s) since $last_tag but the Unreleased section is
        still the placeholder. Describe what changed, or move it into a
        version section if you are cutting a release.
EOF
        status=1
    else
        echo "  ok   Unreleased section ($commits_since commit(s) since $last_tag)"
    fi
fi

if [ "$status" -ne 0 ]; then
    echo >&2
    echo "docs site is out of sync — see the failures above." >&2
    exit 1
fi

echo "docs site is in sync with v$VERSION"
